### ISSUE TITLE
use of textwrap.dedent

### ISSUE THREAD

**Issue by kylebarron** [vatlab/sos-stata#1]
Re https://github.com/vatlab/sos-stata/blob/1a1ad12032cc71c4aefeb20d07798ab6b2a857a2/src/sos_stata/kernel.py#L53-L58

I find that [textwrap.dedent](https://docs.python.org/3.6/library/textwrap.html#textwrap.dedent) is helpful with this. You can define
```py
for i in [1, 2]:
	for j in ...:
		...
        code = f'''\ 
        local _olddir : pwd 
        cd {temp_dir} 
        save data_{idx}.dta 
        cd `_olddir' 
        ''' 
		from textwrap import dedent
		dedented_code = dedent(code)
```

**Comment by BoPeng** [comment]
That makes the code read better, at a slight cost in performance?

Anyway, as you can see from the code, right now `sos-stata` simply save Stata datasets and read in `pandas`, or save in `pandas` and load in Stata. The `%get a b --from Stata` is bogus because there is only one dataset to get, but it is allowed just for consistency. Let me know if you have any comment.

**Comment by kylebarron** [comment]
I think the code is a lot cleaner, and the cost in performance is like 1-2 microseconds. It's four lines of strings...

I think the code looks fine other than that comment

**Comment by BoPeng** [comment]
I agree. Thanks.
